#!/usr/bin/env bash
# accepts two arguments for domain and subdomain

get_record_info() {
    local domain=$1
    local subdomain=$2
    local record_type

    if [[ -z $subdomain ]]; then
        subdomains=("www" "lb-01" "web-01" "web-02")
    else
        subdomains=("$subdomain")
    fi

    for sub in "${subdomains[@]}"; do
        record_type=$(dig "$sub"."$domain" +short)
        echo "The subdomain $sub is a $record_type record and points to $record_type"
    done
}

get_record_info "$1" "$2"
