#!/usr/bin/env bash
# /redirect_me is redirecting to another page.

# Install Nginx
apt-get update
apt-get -y install nginx

# Configure Nginx
sed -i '/^server {/a \
\
    location \/redirect_me {\n\
        return 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n\
    }\n' /etc/nginx/sites-available/default

# Restart Nginx
service nginx restart
