#!/usr/bin/env bash
# have a custom 404 page that contains the string Ceci n'est pas une page.

error_page 404 /custom_404.html;
location = /custom_404.html {
    internal;
    root /var/www/html;
    echo "Ceci n'est pas une page";
}
