#!/usr/bin/env bash
# pings an IP address passed as an argument.

# Check if an IP address argument is provided
if [ $# -eq 0 ]; then
    echo "Usage: $0 {IP_ADDRESS}"
    exit 1
fi

# Extract the IP address from the argument
ip_address=$1

# Ping the IP address 5 times and display the result
ping_result=$(ping -c 5 "$ip_address")

echo "$ping_result"
