#!/usr/bin/env bash
# This script tells the story of /etc/passwd

while IFS=':' read -r username _ uid gid _ home shell; do
    group_name=$(getent group "$gid" | cut -d ':' -f 1)
    pass=$(grep "^$username:" /etc/shadow | cut -d ':' -f 2)
    echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $pass, more info about the user here: $group_name"
done < /etc/passwd
